### ISSUE TITLE
the identification code

### ISSUE THREAD

**Issue by ohtiger** [gist-ailab/teaching-where-to-look#10]
sir, could you release the code of identification.

**Comment by tjdhg456** [comment]
Hi thank you for your interest.

First, I utilized the tinyface inference code from Adaface(CVPR 2022 oral) github.

I'll upload identification code.

**Comment by ohtiger** [comment]
I am learning how to write code about identification , it's appreciated that if you can upload the identification code as soon as possible.

**Comment by guzejungithub** [comment]
sir,thank you for your share.your work is so impressed.could you release the code of  Face detection？And，I wang to learn your work about how to deal with the image size when face detection.resize to 32x to gaussian bule to ordinary size?because  the atttion map dimention from high  resolution is difference from the low . thans for your help .

**Comment by tangxxxxxx** [comment]
> I am learning how to write code about identification , it's appreciated that if you can upload the identification code as soon as possible.
I am also writing code about identification recently, maybe we can communicate

**Comment by ohtiger** [comment]
> > I am learning how to write code about identification , it's appreciated that if you can upload the identification code as soon as possible.
> > I am also writing code about identification recently, maybe we can communicate

can you leave your email or other contact way.

**Comment by tangxxxxxx** [comment]
> 

tangshulei120@gmail.com

**Comment by tjdhg456** [comment]
Reference this page!

I employed this code (https://github.com/mk-minchul/AdaFace/tree/master/validation_lq)
