### ISSUE TITLE
identification code

### ISSUE THREAD

**Issue by Farisalem** [gist-ailab/teaching-where-to-look#13]
hello
your work is amazing. but how can I have identification code part?
or at least guide me how to use the code in adaface(CVPR 2022 oral) that you have introduced... 
this is really important for me.
thank you in advance.

**Comment by fairy3333** [comment]
Also waiting, it's appreciated that if author can upload the identification code!

**Comment by tjdhg456** [comment]
Hi! Thank you for your interest. 
I'll upload the identification code until next week.

**Comment by tjdhg456** [comment]
Hello.
Update the identification code with pre-trained checkpoint.
If you have any further question about identification code, ask via another issues!
Thank you.

**Comment by lilydablue** [comment]
> Also waiting, it's appreciated that if author can upload the identification code!

hello. I wanted to know if you have run the identification code or not. and did you get any errors? because I have got some issues.

**Comment by fairy3333** [comment]
I run the identification code&nbsp;as soon as I received your email. I also get errors!&nbsp;
"probe images : 0
&nbsp;gallery images : 0
&nbsp;...
&nbsp;ValueError: need at least one array to concatenate"
&nbsp;Look forward to your update!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gist-ailab/teaching-where-to-look"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gist-ailab/teaching-where-to-look] identification code (Issue #13)





  
Also waiting, it's appreciated that if author can upload the identification code!
  
hello. I wanted to know if you have run the identification code or not. and did you get any errors? because I have got some issues.

**Comment by lilydablue** [comment]
> I run the identification code&nbsp;as soon as I received your email. I also get errors!&nbsp; "probe images : 0 &nbsp;gallery images : 0 &nbsp;... &nbsp;ValueError: need at least one array to concatenate" &nbsp;Look forward to your update!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gist-ailab/teaching-where-to-look" ***@***.***&gt;; 发送时间:&nbsp;2023年4月25日(星期二) 晚上10:14 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gist-ailab/teaching-where-to-look] identification code (Issue #13) Also waiting, it's appreciated that if author can upload the identification code! hello. I wanted to know if you have run the identification code or not. and did you get any errors? because I have got some issues. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

I had this error too. and I changed my directory to :
--tinyface_dir /content/tinyface/tinyface/Testing_Set
and now it is ok.

**Comment by lilydablue** [comment]
> I run the identification code&nbsp;as soon as I received your email. I also get errors!&nbsp; "probe images : 0 &nbsp;gallery images : 0 &nbsp;... &nbsp;ValueError: need at least one array to concatenate" &nbsp;Look forward to your update!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gist-ailab/teaching-where-to-look" ***@***.***&gt;; 发送时间:&nbsp;2023年4月25日(星期二) 晚上10:14 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gist-ailab/teaching-where-to-look] identification code (Issue #13) Also waiting, it's appreciated that if author can upload the identification code! hello. I wanted to know if you have run the identification code or not. and did you get any errors? because I have got some issues. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

maybe you have downloaded the wrong dataset as I did. :))
